main:
  - name: "Home"
    pageRef: "/"
    weight: 1
  - name: "Projects"
    pageRef: "/projects"
    weight: 10
  - name: "Useful Coommunities"
    pageRef: "/community"
    weight: 20
  - name: "Blog"
    pageRef: "/blog"
    weight: 30
  - name: "Useful Articles"
    pageRef: "/articles"
    weight: 40