# Build output directory
output_dir = "HTML"
# Title of the site
title = "Harry Min Khant"
base_url = "https://harrymkt.github.io"
theme = "zluinav"
# Default author to be used if the page does not have set one.
author = "Harry Min Khant"
# Feed filename
feed_filenames = ["rss.xml"]
# We don't need Sass
compile_sass = false
# Search feature is currently not supported in this theme
build_search_index = false
# Default language
default_language = "en"

[extra]
  [extra.menus]
    [[extra.menus.main]]
      name = "Home"
      url = "/"
    [[extra.menus.main]]
      name = "Projects"
      url = "/projects"
    [[extra.menus.main]]
      name = "Blog"
      url = "/blog"
    [[extra.menus.main]]
      name = "Useful Communities"
      url = "/community"
    [[extra.menus.main]]
      name = "Useful Articles"
      url = "/articles"