baseURL = "https://harrymkt.github.io"
title = "Harry Min Khant"
cleanDestinationDir = true
publishDir = "HTML"
theme = "hguinav"
[menus]
	[[menus.main]]
		name = "Home"
		pageRef = "/"
		weight = 10
	[[menus.main]]
		name = "Projects"
		pageRef = "/projects"
		weight = 20
	[[menus.main]]
		name = "Blog"
		pageRef = "/blog"
		weight = 30
	[[menus.main]]
		name = "Useful Communities"
		pageRef = "/community"
		weight = 40
	[[menus.main]]
		name = "Useful Articles"
		pageRef = "/articles"
		weight = 50